<!-- white box for delivery order -->
<div class="orderBox">
	<!-- order information -->
	<div class="orderInfo">
		<h1>배달 음식 온라인 주문 서비스<h1>
		<span>주문 지역에 맞춘 다양한 배달 음식 정보 제공<br>YOGIYO로 새로운 음식 배달 서비스를 경험하세요.</span>
	</div>
	<!-- order area search bar -->
	<div class="orderArea">
		<label id="orderArea_info">주문하시는 지역의 동 이름을 입력하세요.</label>
		<input type="text" id="orderArea" value="" placeholder="예) 서울시 강남구 논현동" name="orderArea" />
	</div>
	<!-- serach button -->
	<div class="search">
		<div class="serachButton">
			<a>검색하기</a>
		</div>
	</div>
</div>
